[providers]
nixpkgs.packages = ["python39"]

[phases.setup]
dependenciesOnly = true

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
