[tool.poetry]
name = "qads-chatbot"
version = "1.0.0"
description = "QADS Chatbot"

[tool.poetry.dependencies]
python = "^3.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
