services:
  - type: web
    name: qads-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py backend.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
